### ISSUE TITLE
After Update to 2.0.6 reauthentication fails

### ISSUE THREAD

**Issue by Palmdale95** [albaintor/homeassistant_electrolux_status#96]
Hi there,

after installing the latest update no reconnect to my electrolux account is possible.
Looks like something went wrong:

Logger: homeassistant.config_entries
Quelle: config_entries.py:594
Erstmals aufgetreten: 10:30:15 (1 Vorkommnisse)
Zuletzt protokolliert: 10:30:15

Error setting up entry XXXXXXXXX for electrolux_status
Traceback (most recent call last):
  File "/config/custom_components/electrolux_status/coordinator.py", line 402, in setup_entities
    appliance.setup(
  File "/config/custom_components/electrolux_status/api.py", line 618, in setup
    if (entity := self.get_entity(static_attribute)) is None:
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/electrolux_status/api.py", line 577, in get_entity
    return electrolux_entity_factory(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Appliance.get_entity.<locals>.electrolux_entity_factory() got an unexpected keyword argument 'entity_name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/electrolux_status/__init__.py", line 71, in async_setup_entry
    await coordinator.setup_entities()
  File "/config/custom_components/electrolux_status/coordinator.py", line 413, in setup_entities
    raise UpdateFailed from exception
homeassistant.helpers.update_coordinator.UpdateFailed

Going back to the previous 2.0.5 solved the issue for now.
